### ISSUE TITLE
账号密码格式

### ISSUE THREAD

**Issue by wealthpanC** [founder-yu/V2free-Checkin#5]
请问下只需要在secret里输入账号密码就行了吧？例如：
....@qq.com
ssddff
这样的格式？

**Comment by founder-yu** [comment]
readme文件添加了对应的图片，请查看，如仍有问题敬请追问

**Comment by wealthpanC** [comment]
现在没有报错了，但是为什么我在日志里没有看见我的账号了？我也不知道成功没有

**Comment by wealthpanC** [comment]
按照您的要求改了，目前还是不行，提醒我run failed
![image](https://user-images.githubusercontent.com/52003323/204198454-1b7f142e-ecc6-4da3-bcd6-96255e91a8e4.png)

**Comment by founder-yu** [comment]
兄弟你再重新fork一份试试，我在你的repository里甚至没看到workflow

**Comment by founder-yu** [comment]
如果还有报错，请把具体的报错截图贴出来

**Comment by wealthpanC** [comment]
还是不行，现在我点star完全没反应，flow.log都没有更新

**Comment by wealthpanC** [comment]
![image](https://user-images.githubusercontent.com/52003323/204237946-bad0d05c-11b0-46b4-a7ce-daa5d07cf2ff.png)

**Comment by founder-yu** [comment]
点击左侧All workflows下的V2freeCheckin，并允许运行

**Comment by founder-yu** [comment]
看来你已经成功了

**Comment by wealthpanC** [comment]
已经好了，谢谢了
